# Generated by Django 5.2.17 on 2026-08-25 10:51

import apps.schools.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('admin', models.ForeignKey(help_text='The School Admin account that owns this school.', on_delete=django.db.models.deletion.PROTECT, related_name='administered_schools', to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('classroom_code', models.CharField(default=apps.schools.models.generate_classroom_code, help_text='Shown to the admin for rosters and handouts; not a login credential.', max_length=12, unique=True, verbose_name='classroom code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'classroom',
                'verbose_name_plural': 'classrooms',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD_TEACHER', 'Lead teacher'), ('ASSISTANT', 'Assistant'), ('THERAPIST', 'Therapist')], default='LEAD_TEACHER', max_length=16, verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='schools.classroom', verbose_name='classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'classroom membership',
                'verbose_name_plural': 'classroom memberships',
                'ordering': ['classroom', 'role'],
                'indexes': [models.Index(fields=['teacher'], name='schools_cla_teacher_422dc1_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'teacher'), name='unique_membership_per_classroom')],
            },
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school'], name='schools_cla_school__fb2a6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_classroom_name_per_school'),
        ),
    ]
