# Generated by Django 5.2.17 on 2026-08-25 17:36

import apps.schools.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('invitation_code', models.CharField(default=apps.schools.models.generate_invitation_code, max_length=8, unique=True, verbose_name='invitation code')),
                ('expires_at', models.DateTimeField(default=apps.schools.models.default_invitation_expiry, verbose_name='expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='schools.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'teacher invitation',
                'verbose_name_plural': 'teacher invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school'], name='schools_tea_school__72f988_idx')],
            },
        ),
    ]
