# Generated by Django 5.2.17 on 2026-08-25 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_teacherinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'email'), name='unique_active_invitation_per_school_email'),
        ),
    ]
