# Generated by Django 5.2.17 on 2026-08-18 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('avatar', models.CharField(choices=[('BOY_1', 'Boy 1'), ('BOY_2', 'Boy 2'), ('GIRL_1', 'Girl 1'), ('GIRL_2', 'Girl 2'), ('CAT', 'Cat'), ('ELEPHANT', 'Elephant')], default='BOY_1', max_length=16, verbose_name='avatar')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='level')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='points')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='streak days')),
                ('last_practised_on', models.DateField(blank=True, null=True, verbose_name='last practised on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('practice_language', models.ForeignKey(help_text="The language this child practises. Separate from the app's interface language, which is a device setting.", on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='content.language', verbose_name='practice language')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_profile_name_per_owner')],
            },
        ),
    ]
