"""Add Profile.share_code.

Written by hand rather than autogenerated: adding a *unique* column to a table
that already has rows needs three steps. Adding it unique in one go would try
to write the same default into every row and violate the constraint.
"""

from django.db import migrations, models

import apps.profiles.models


def populate_share_codes(apps_registry, schema_editor):
    """Give every existing profile its own code."""
    Profile = apps_registry.get_model("profiles", "Profile")
    used = set()

    for profile in Profile.objects.filter(share_code__isnull=True):
        code = apps.profiles.models.generate_share_code()
        while code in used:
            code = apps.profiles.models.generate_share_code()
        used.add(code)

        profile.share_code = code
        profile.save(update_fields=["share_code"])


def clear_share_codes(apps_registry, schema_editor):
    Profile = apps_registry.get_model("profiles", "Profile")
    Profile.objects.update(share_code=None)


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_initial")]

    operations = [
        # 1. Nullable and non-unique, so existing rows are accepted.
        migrations.AddField(
            model_name="profile",
            name="share_code",
            field=models.CharField(
                max_length=16, null=True, verbose_name="share code"
            ),
        ),
        # 2. Backfill.
        migrations.RunPython(populate_share_codes, clear_share_codes),
        # 3. Now that every row has a value, apply the real constraint.
        migrations.AlterField(
            model_name="profile",
            name="share_code",
            field=models.CharField(
                default=apps.profiles.models.generate_share_code,
                help_text=(
                    "Given to a teacher so they can follow this learner. "
                    "Regenerating it revokes any code already handed out."
                ),
                max_length=16,
                unique=True,
                verbose_name="share code",
            ),
        ),
    ]
