# Generated by Django 5.2.17 on 2026-08-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_share_code'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.classroom', verbose_name='classroom'),
        ),
    ]
