# Generated by Django 5.2.17 on 2026-08-19 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FIRST_PRACTICE', 'First Practice'), ('FIRST_PERFECT_SCORE', 'First 90+ Score'), ('TEN_WORDS', '10 Words Learned'), ('TWENTY_FIVE_WORDS', '25 Words Learned'), ('FIRST_LESSON', 'First Lesson Completed'), ('SEVEN_DAY_STREAK', '7 Day Streak')], max_length=32, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('name_ms', models.CharField(blank=True, max_length=120, verbose_name='name (Malay)')),
                ('description_ms', models.CharField(blank=True, max_length=255, verbose_name='description (Malay)')),
                ('icon', models.CharField(blank=True, max_length=16, verbose_name='icon')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='bonus points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_words', models.PositiveIntegerField(default=0, help_text='Distinct words with at least one passing attempt.', verbose_name='completed words')),
                ('total_words', models.PositiveIntegerField(default=0, verbose_name='total words')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='attempts')),
                ('average_score', models.FloatField(blank=True, null=True, verbose_name='average score')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='last accessed')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.lesson')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'lesson progress',
                'verbose_name_plural': 'lesson progress',
                'ordering': ['-last_accessed'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'lesson'), name='unique_progress_per_lesson')],
            },
        ),
        migrations.CreateModel(
            name='ProfileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='progress.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'earned achievement',
                'verbose_name_plural': 'earned achievements',
                'ordering': ['-earned_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'achievement'), name='unique_achievement_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='StudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_links', to='profiles.profile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student link',
                'verbose_name_plural': 'student links',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('supervisor', 'profile'), name='unique_supervisor_link')],
            },
        ),
    ]
