# Generated by Django 5.2.17 on 2026-08-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('ms', 'Bahasa Melayu')], max_length=8, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('locale', models.CharField(help_text='BCP-47 locale passed to Azure Speech, e.g. en-US.', max_length=16, unique=True, verbose_name='locale')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('supports_pronunciation_assessment', models.BooleanField(default=True, verbose_name='supports pronunciation assessment')),
                ('supports_prosody', models.BooleanField(default=False, help_text='Intonation, stress and rhythm. Azure supports en-US only.', verbose_name='supports prosody')),
                ('supports_phoneme_names', models.BooleanField(default=False, help_text='Whether Azure returns phoneme identities (IPA) or only scores.', verbose_name='supports phoneme names')),
                ('supports_syllable_scores', models.BooleanField(default=False, verbose_name='supports syllable scores')),
                ('capabilities_verified_on', models.DateField(blank=True, help_text="When these flags were last checked against Azure's docs.", null=True, verbose_name='capabilities verified on')),
                ('tts_voice', models.CharField(blank=True, help_text='Azure neural voice used to pronounce words.', max_length=64, verbose_name='text-to-speech voice')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Emoji shown on the category chip.', max_length=16, verbose_name='icon')),
                ('image_url', models.URLField(blank=True, verbose_name='image URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='content.language')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['language__code', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate')], default='BEGINNER', max_length=16, verbose_name='difficulty')),
                ('image_url', models.URLField(blank=True, verbose_name='image URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.category')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Reference text for pronunciation assessment.', max_length=120, verbose_name='word')),
                ('meaning', models.TextField(blank=True, verbose_name='meaning')),
                ('example_sentence', models.TextField(blank=True, verbose_name='example sentence')),
                ('image_url', models.URLField(blank=True, verbose_name='image URL')),
                ('audio_url', models.URLField(blank=True, help_text='Optional pre-recorded audio. Falls back to TTS when empty.', verbose_name='audio URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('distractors', models.ManyToManyField(blank=True, help_text='Wrong options offered alongside this word in quizzes.', related_name='distractor_for', to='content.word', verbose_name='distractors')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='content.lesson')),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
                'ordering': ['lesson', 'order', 'text'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='unique_category_slug_per_language'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('lesson', 'text'), name='unique_word_per_lesson'),
        ),
    ]
