# Generated by Django 5.2.17 on 2026-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='emoji',
            field=models.CharField(blank=True, help_text='Shown when no illustration is available. Without it a Listen round is unplayable, because the word is hidden and every option would look identical.', max_length=8, verbose_name='emoji'),
        ),
    ]
