# Generated by Django 5.2.17 on 2026-08-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_word_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='assessment_provider',
            field=models.CharField(choices=[('default', 'Use SPEECH_PROVIDER setting'), ('azure', 'Azure AI Speech'), ('speechace', 'SpeechAce'), ('mock', 'Mock (no real assessment)')], default='default', help_text='Which engine scores this language. Set per language because coverage differs: SpeechAce has no Malay, so ms-MY can only use Azure or the mock.', max_length=16, verbose_name='assessment provider'),
        ),
    ]
