# Generated by Django 5.2.17 on 2026-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_language_assessment_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='assessment_provider',
        ),
        migrations.RemoveField(
            model_name='language',
            name='capabilities_verified_on',
        ),
        migrations.RemoveField(
            model_name='language',
            name='supports_phoneme_names',
        ),
        migrations.RemoveField(
            model_name='language',
            name='supports_pronunciation_assessment',
        ),
        migrations.RemoveField(
            model_name='language',
            name='supports_prosody',
        ),
        migrations.RemoveField(
            model_name='language',
            name='supports_syllable_scores',
        ),
        migrations.AlterField(
            model_name='language',
            name='locale',
            field=models.CharField(help_text='BCP-47 locale, e.g. en-US. Used for text-to-speech.', max_length=16, unique=True, verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='language',
            name='tts_voice',
            field=models.CharField(blank=True, help_text='Voice identifier used when reading a word aloud.', max_length=64, verbose_name='text-to-speech voice'),
        ),
    ]
