# Generated by Django 5.2.17 on 2026-08-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='schools.school', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('SCHOOL_ADMIN', 'School admin')], default='STUDENT', max_length=16, verbose_name='role'),
        ),
    ]
