# Generated by Django 5.2.17 on 2026-08-19 01:04

import apps.practice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, verbose_name='language code')),
                ('locale', models.CharField(max_length=16, verbose_name='locale')),
                ('reference_text', models.CharField(max_length=120, verbose_name='reference text')),
                ('recognized_text', models.CharField(blank=True, max_length=255, verbose_name='recognized text')),
                ('accuracy_score', models.FloatField(blank=True, null=True, verbose_name='accuracy')),
                ('fluency_score', models.FloatField(blank=True, null=True, verbose_name='fluency')),
                ('pronunciation_score', models.FloatField(blank=True, null=True, verbose_name='pronunciation')),
                ('completeness_score', models.FloatField(blank=True, null=True, verbose_name='completeness')),
                ('prosody_score', models.FloatField(blank=True, help_text='Null where the locale does not support prosody (ms-MY).', null=True, verbose_name='prosody')),
                ('error_type', models.CharField(blank=True, max_length=32, verbose_name='error type')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='points awarded')),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.practice.models.attempt_audio_path, verbose_name='audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='profiles.profile')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.word')),
            ],
            options={
                'verbose_name': 'practice attempt',
                'verbose_name_plural': 'practice attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='practice_pr_profile_26af14_idx'), models.Index(fields=['profile', 'word'], name='practice_pr_profile_740b08_idx')],
            },
        ),
    ]
