# Generated by Django 5.2.17 on 2026-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_quizsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceattempt',
            name='accuracy_score',
        ),
        migrations.RemoveField(
            model_name='practiceattempt',
            name='error_type',
        ),
        migrations.RemoveField(
            model_name='practiceattempt',
            name='fluency_score',
        ),
        migrations.RemoveField(
            model_name='practiceattempt',
            name='prosody_score',
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text="Whisper's own confidence in the transcription.", null=True, verbose_name='confidence'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='errors',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of {type, expected, detected}.', verbose_name='errors'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='Phonetic-feature distance between reference and spoken.', null=True, verbose_name='similarity'),
        ),
        migrations.AlterField(
            model_name='practiceattempt',
            name='pronunciation_score',
            field=models.FloatField(blank=True, help_text='The single weighted score shown to the child.', null=True, verbose_name='pronunciation'),
        ),
    ]
