# Generated by Django 5.2.17 on 2026-08-22 04:12

import apps.practice.debug_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_remove_practiceattempt_accuracy_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationDebugAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.CharField(max_length=120, verbose_name='reference text')),
                ('recognized_text', models.CharField(blank=True, max_length=255, verbose_name='recognized text')),
                ('language_code', models.CharField(max_length=8, verbose_name='language code')),
                ('similarity_score', models.FloatField(blank=True, null=True, verbose_name='similarity')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='confidence')),
                ('completeness_score', models.FloatField(blank=True, null=True, verbose_name='completeness')),
                ('pronunciation_score', models.FloatField(blank=True, null=True, verbose_name='pronunciation')),
                ('phoneme_distance', models.PositiveIntegerField(blank=True, null=True, verbose_name='phoneme edit distance')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='errors')),
                ('processing_time_ms', models.FloatField(blank=True, null=True, verbose_name='total processing time (ms)')),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.practice.debug_models.debug_audio_path, verbose_name='audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronunciation_debug_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pronunciation debug attempt',
                'verbose_name_plural': 'pronunciation debug attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
